[package]
name = "hoppy-tester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
read_buffer = "1.2.0"
serialport = "4.2.0"
